version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run build
      - npm prune --production
  build:
    commands:
      - >
        aws cloudformation package
        --template template.yml
        --s3-bucket $S3_BUCKET
        --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml
