AWSTemplateFormatVersion: 2010-09-09
Description: Lambda application apollo-todo-list

Transform: AWS::Serverless-2016-10-31

Parameters:
  AppId:
    Type: String
  NodeEnv:
    Type: String
    Default: "production"
  DatabaseHost:
    Type: String
    Default: ""
  DatabaseUsername:
    Type: String
    Default: "postgres"
  DatabasePassword:
    Type: String
    Default: "postgres"
  JwtSecret:
    Type: String
    Default: ""

Globals:
  Function:
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'
    Runtime: nodejs14.x
    Environment:
      Variables:
        NODE_ENV: !Ref NodeEnv
        DATABASE_HOST: !Ref DatabaseHost
        DATABASE_USERNAME: !Ref DatabaseUsername
        DATABASE_PASSWORD: !Ref DatabasePassword
        JWT_SECRET: !Ref JwtSecret

Resources:
  graphql:
    Type: AWS::Serverless::Function
    FunctionName: apollo-graphql
    Properties:
      CodeUri: ./
      Handler: dist/index.graphqlHandler
      MemorySize: 128
      Timeout: 60
      Description: An endpoint for GraphQL queries.
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: graphql
            Method: GET
        PostEvent:
          Type: Api
          Properties:
            Path: graphql
            Method: POST
